// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfjeaievpekysbcoptxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmamVhaWV2cGVreXNiY29wdHhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MDcwNjUsImV4cCI6MjA1NjM4MzA2NX0.yzGdeYZuwtgJGQD8ly6lDYBoPqqmWOANr4aaOczP1xU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});